fail_fast: true
repos:
  # Code formatting and import organization
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix, --config=pyproject.toml]
      - id: ruff-format

  # - repo: local
  #   hooks:
  #     - id: ty
  #       name: ty
  #       entry: ty
  #       args:
  #         - check
  #         - --exit-zero
  #         - --output-format=concise
  #       language: python
  #       additional_dependencies:
  #         - ty==0.0.1a21
  #       types_or: [python, pyi]

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
        exclude: ^examples/

  # # Test hooks
  # - repo: local
  #   hooks:
  #     - id: pytest-unit-tests
  #       name: Run unit tests with coverage
  #       entry: bash -c "ARBOR_MOCK_GPU=1 uv run --only-group dev pytest tests/server/ --cov=arbor --cov-report=term-missing --cov-report=html --cov-fail-under=30 -v --tb=short --timeout=45"
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true

  #     - id: pytest-integration-tests
  #       name: Run integration tests
  #       entry: bash -c "ARBOR_MOCK_GPU=1 uv run --only-group dev pytest tests/integration/ -v --tb=short --timeout=90 -k 'not test_openai_cancel_fine_tune_job'"
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
