[project]
name = "dspy-trainer"
version = "0.1.0"
description = ""
authors = [
    {name = "Noah Ziems",email = "nziems2@nd.edu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "click",
    "python-multipart (>=0.0.20,<0.0.21)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "transformers (>=4.49.0,<5.0.0)",
    "trl (>=0.15.2,<0.16.0)",
    "peft (>=0.14.0,<0.15.0)",
]

[project.scripts]
dspy-trainer = "dspy_trainer.cli:cli"

[tool.poetry]
packages = [{include = "dspy_trainer", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
