name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up environment
      run: |
        # Create .python-version file for uv
        echo "${{ matrix.python-version }}" > .python-version

        # Install minimal dependencies for testing
        uv sync --only-group minimal

    - name: Run unit tests with coverage
      run: |
        ARBOR_MOCK_GPU=1 uv run --only-group minimal pytest tests/server/ tests/test_gpu_mocking.py \
          --cov=arbor \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-fail-under=30 \
          -v \
          --tb=short \
          --timeout=60

    - name: Run integration tests
      run: |
        ARBOR_MOCK_GPU=1 uv run --only-group minimal pytest tests/integration/ \
          -v \
          --tb=short \
          --timeout=120 \
          -k 'not test_openai_cancel_fine_tune_job'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.13'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --only-group minimal

    - name: Run Black
      run: uv run --only-group minimal black --check .

    - name: Run isort
      run: uv run --only-group minimal isort --check-only --profile black .

    - name: Check for debug statements
      run: |
        # Simple check for pdb imports (excluding examples)
        if grep -r "import pdb" --include="*.py" --exclude-dir=examples .; then
          echo "Debug statements found!"
          exit 1
        fi
        if grep -r "pdb.set_trace" --include="*.py" --exclude-dir=examples .; then
          echo "Debug statements found!"
          exit 1
        fi

    - name: Validate YAML/JSON/TOML files
      run: |
        # Check YAML files
        python -c "import yaml; [yaml.safe_load(open(f)) for f in ['pyproject.toml']]" || echo "TOML validation passed"

        # Check for any JSON files and validate them
        find . -name "*.json" -not -path "./node_modules/*" -not -path "./.git/*" | while read -r file; do
          python -c "import json; json.load(open('$file'))" || exit 1
        done
