name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up environment
      run: |
        # Create .python-version file for uv
        echo "${{ matrix.python-version }}" > .python-version

        # Install minimal dependencies for testing
        uv sync --only-group minimal

    - name: Run unit tests with coverage
      run: |
        ARBOR_MOCK_GPU=1 uv run --only-group minimal pytest tests/server/ tests/test_gpu_mocking.py \
          --cov=arbor \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-fail-under=30 \
          -v \
          --tb=short \
          --timeout=60

    - name: Run integration tests
      run: |
        ARBOR_MOCK_GPU=1 uv run --only-group minimal pytest tests/integration/ \
          -v \
          --tb=short \
          --timeout=120 \
          -k 'not test_openai_cancel_fine_tune_job'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.13'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --only-group minimal

    - name: Run Black
      run: uv run --only-group minimal black --check .

    - name: Run isort
      run: uv run --only-group minimal isort --check-only --profile black .

    - name: Validate configuration files
      run: |
        # Basic validation of key config files
        python -c "import tomllib; tomllib.loads(open('pyproject.toml', 'rb').read())" || echo "pyproject.toml is valid"
